### PR TITLE
Split out a core library with fewer dependencies

### PR DESCRIPTION
**Pull request by anka-213**
This is useful for the ghcjs stuff

### CODE REVIEW

**Comment by Martin-Strecker** [comment]
Thanks! In principle, this looks reasonable to me. But I have a naive question concerning Git: will Git be able to recognize which files correspond so that changes made to a file (say, the parser) get correctly integrated in the split-to-packages branch, in spite of the different file structure?

**Comment by anka-213** [comment]
It should be able to do that, but as long as we merge it in quickly, there shouldn't be any merge conflicts even if it didn't. Unless you have unmerged changes in the parser?

**Comment by Martin-Strecker** [comment]
I don't have any changes right now, but I just wonder for the future how we keep the split-to-packages repo in sync with the development (which, I assume, will continue in main, smtgen etc, unless we close these branches and start new branches from split-to-packages).

**Comment by anka-213** [comment]
We would migrate to only using the split version as soon as this is merged. We shouldn't have multiple long-running parallel branches running.

**Comment by anka-213** [comment]
In other words, this would be the new main that everything builds on top of.

**Pull request merged**
