### PR TITLE
[Finalized] Clear diagnostics #19

### LINKED ISSUE #19: Clear diagnostics when they are no longer relevant.
If you give no diagnostics, it will interpret it as no change instead of as no errors.

See here
https://hackage.haskell.org/package/lsp-1.1.1.0/docs/Language-LSP-Diagnostics.html

### PR DESCRIPTION
**Pull request by ffrixslee**
Resolves #19

### CODE REVIEW

**Comment by anka-213** [comment]
This is just a comment change. Where are the rest of the changes?

**Comment by anka-213** [comment]
Maybe they were already merged by something else

**Comment by ffrixslee** [comment]
> Maybe they were already merged by something else

@anka-213 yes, sorry about that ! It got merged by the previous commit...I opened the pull request so that it could close the linked issue 😅 (Probably unnecessary?)

**Comment by anka-213** [comment]
No, it's good. But I'm not completely sure if these fixes actually fixed the problem completely, so I was planning to look on how to change when reviewing the pull request.

**Comment by ffrixslee** [comment]
@anka-213 Ohhh do you want me to git revert? Though the only change I made was that one line:
publishDiagnostics 100 nuri Nothing (Map.singleton(Just "lexer")(Data.SortedList.toSortedList [])) 
And importing the relevant libraries in the .cabal file !

**Comment by anka-213** [comment]
No, it's ok. I can just look at the commits and see what might need changing.

**Comment by kharus** [comment]
Shall we close this PR?
Currently it just hangs in the list of PRs.
There is no code to merge

**Pull request closed without merging**
