### PR TITLE
Added CLI subcommand support 

### PR DESCRIPTION
**Pull request by alfredats**
As requested by #6.

I've had to make a few changes to the ToGF module to get it to work on a per-language basis, so am pulling in @inariksit for the review.

### CODE REVIEW

**Comment by alfredats** [comment]
The current subcommand structure is as follows: 
```
cclaw/baby-l4 (arg-opts*) % stack run -- l4 --help        
mini-l4 - minimum l4? miniturised l4?

Usage: l4 COMMAND Filename

Available options:
  -h,--help                Show this help text

Available commands:
  all                      Prints all available formats
```bash

**Comment by alfredats** [comment]
with the `all` subcommand (currently the same as the `gf all` subcommand:
```
cclaw/baby-l4 (arg-opts*) % stack run -- l4 gf all l4/mini.l4  
Program [Mapping (SRng {start = Pos {line = 4, col = 0}, end = Pos {line = 4, col = 21}}) "is_legal" "legal_1_A",Mapping (SRng {start = Pos {line = 5, col = 0}, end = Pos {line = 5, col = 24}}) "Business" "business_1_N"] [] [VarDecl "myNumber" IntT,VarDecl "myBusiness" (ClassT (ClsNm "Business")),VarDecl "is_legal" (FunT (ClassT (ClsNm "Business")) BoolT)] [] []
PAtom (AKind Nat (IVar (VString "myNumber")))
myNumber is a number
myNumber är ett tal
PAtom (AKind (KInd (IVarN Business)) (IVar (VString "myBusiness")))
myBusiness has type business
myBusiness är av typen affär
PAtom (AKind (KFun (KInd (IVarN Business)) Boolean) (IVar (VString "is_legal")))
is_legal is a function from the type business to a Boolean value
is_legal är en funktion från typen affär till en boolesk variabel
```

**Comment by alfredats** [comment]
with `gf en`:

```
cclaw/baby-l4 (arg-opts*) % stack run -- l4 gf en l4/mini.l4 
Program [Mapping (SRng {start = Pos {line = 4, col = 0}, end = Pos {line = 4, col = 21}}) "is_legal" "legal_1_A",Mapping (SRng {start = Pos {line = 5, col = 0}, end = Pos {line = 5, col = 24}}) "Business" "business_1_N"] [] [VarDecl "myNumber" IntT,VarDecl "myBusiness" (ClassT (ClsNm "Business")),VarDecl "is_legal" (FunT (ClassT (ClsNm "Business")) BoolT)] [] []
PAtom (AKind Nat (IVar (VString "myNumber")))
myNumber is a number
PAtom (AKind (KInd (IVarN Business)) (IVar (VString "myBusiness")))
myBusiness has type business
PAtom (AKind (KFun (KInd (IVarN Business)) Boolean) (IVar (VString "is_legal")))
is_legal is a function from the type business to a Boolean value
```

with `gf swe`:
```
cclaw/baby-l4 (arg-opts*) % stack run -- l4 gf swe l4/mini.l4  
Program [Mapping (SRng {start = Pos {line = 4, col = 0}, end = Pos {line = 4, col = 21}}) "is_legal" "legal_1_A",Mapping (SRng {start = Pos {line = 5, col = 0}, end = Pos {line = 5, col = 24}}) "Business" "business_1_N"] [] [VarDecl "myNumber" IntT,VarDecl "myBusiness" (ClassT (ClsNm "Business")),VarDecl "is_legal" (FunT (ClassT (ClsNm "Business")) BoolT)] [] []
PAtom (AKind Nat (IVar (VString "myNumber")))
myNumber är ett tal
PAtom (AKind (KInd (IVarN Business)) (IVar (VString "myBusiness")))
myBusiness är av typen affär
PAtom (AKind (KFun (KInd (IVarN Business)) Boolean) (IVar (VString "is_legal")))
is_legal är en funktion från typen affär till en boolesk variabel
```

**Comment by mengwong** [comment]
Can I suggest the gf en and gf swe commands “comment out” the AST by prefixing it with, say, ##

On 7 Mar 2021, at 5:37 PM, Alfred A. <notifications@github.com> wrote:

﻿

with gf en:

cclaw/baby-l4 (arg-opts*) % stack run -- l4 gf en l4/mini.l4
Program [Mapping (SRng {start = Pos {line = 4, col = 0}, end = Pos {line = 4, col = 21}}) "is_legal" "legal_1_A",Mapping (SRng {start = Pos {line = 5, col = 0}, end = Pos {line = 5, col = 24}}) "Business" "business_1_N"] [] [VarDecl "myNumber" IntT,VarDecl "myBusiness" (ClassT (ClsNm "Business")),VarDecl "is_legal" (FunT (ClassT (ClsNm "Business")) BoolT)] [] []
PAtom (AKind Nat (IVar (VString "myNumber")))
myNumber is a number
PAtom (AKind (KInd (IVarN Business)) (IVar (VString "myBusiness")))
myBusiness has type business
PAtom (AKind (KFun (KInd (IVarN Business)) Boolean) (IVar (VString "is_legal")))
is_legal is a function from the type business to a Boolean value


with gf swe:

cclaw/baby-l4 (arg-opts*) % stack run -- l4 gf swe l4/mini.l4
Program [Mapping (SRng {start = Pos {line = 4, col = 0}, end = Pos {line = 4, col = 21}}) "is_legal" "legal_1_A",Mapping (SRng {start = Pos {line = 5, col = 0}, end = Pos {line = 5, col = 24}}) "Business" "business_1_N"] [] [VarDecl "myNumber" IntT,VarDecl "myBusiness" (ClassT (ClsNm "Business")),VarDecl "is_legal" (FunT (ClassT (ClsNm "Business")) BoolT)] [] []
PAtom (AKind Nat (IVar (VString "myNumber")))
myNumber är ett tal
PAtom (AKind (KInd (IVarN Business)) (IVar (VString "myBusiness")))
myBusiness är av typen affär
PAtom (AKind (KFun (KInd (IVarN Business)) Boolean) (IVar (VString "is_legal")))
is_legal är en funktion från typen affär till en boolesk variabel

**Comment by mengwong** [comment]
After discussion – let's add flags – so we have

l4 gf en --astgf --asths

--astgf to show the gf ast
--asths to show the haskell ast

but always prefixed with two // as comments

**Review by inariksit — APPROVED** [review]
Looks good to me!

**Comment by alfredats** [comment]
Have updated the current executable to have the options as follows: 
```
 cclaw/baby-l4 (arg-opts*) % stack run -- l4 --help

mini-l4 - minimum l4? miniturised l4?

Usage: l4 COMMAND [--astHS] [--astGF] Filename

Available options:
  --astHS                  Print Haskell AST to STDERR
  --astGF                  Print GF AST to STDERR
  -h,--help                Show this help text

Available commands:
  all                      Prints all available formats
  gf                       Prints natLang format (subcommands: en, my)
```

running it with the astHS & astGF flags respectively print the asts to STDERR as required
```
cclaw/baby-l4 (arg-opts*) % stack run -- l4 all --astHS --astGF l4/mini.l4 2> test.err       
myNumber is a number
myNumber är ett tal
myBusiness has type business
myBusiness är av typen affär
is_legal is a function from the type business to a Boolean value
is_legal är en funktion från typen affär till en boolesk variabel
```
```
cclaw/baby-l4 (arg-opts*) % cat test.err                                                     SMUs-Macbook
Program {lexiconOfProgram = [Mapping (SRng {start = Pos {line = 4, col = 0}, end = Pos {line = 4, col = 21}}) "is_legal" "legal_1_A",Mapping (SRng {start = Pos {line = 5, col = 0}, end = Pos {line = 5, col = 24}}) "Business" "business_1_N"], classDeclsOfProgram = [ClassDecl {nameOfClassDecl = ClsNm "Object", defOfClassDecl = ClassDef {supersOfClassDef = [], fieldsOfClassDef = []}},ClassDecl {nameOfClassDecl = ClsNm "Boolean", defOfClassDecl = ClassDef {supersOfClassDef = [ClsNm "Object"], fieldsOfClassDef = []}},ClassDecl {nameOfClassDecl = ClsNm "Number", defOfClassDecl = ClassDef {supersOfClassDef = [ClsNm "Object"], fieldsOfClassDef = []}},ClassDecl {nameOfClassDecl = ClsNm "Float", defOfClassDecl = ClassDef {supersOfClassDef = [ClsNm "Number",ClsNm "Object"], fieldsOfClassDef = []}},ClassDecl {nameOfClassDecl = ClsNm "Integer", defOfClassDecl = ClassDef {supersOfClassDef = [ClsNm "Number",ClsNm "Object"], fieldsOfClassDef = []}},ClassDecl {nameOfClassDecl = ClsNm "String", defOfClassDecl = ClassDef {supersOfClassDef = [ClsNm "Object"], fieldsOfClassDef = []}},ClassDecl {nameOfClassDecl = ClsNm "Class", defOfClassDecl = ClassDef {supersOfClassDef = [ClsNm "Object"], fieldsOfClassDef = []}}], globalsOfProgram = [VarDecl "myNumber" IntT,VarDecl "myBusiness" (ClassT (ClsNm "Business")),VarDecl "is_legal" (FunT (ClassT (ClsNm "Business")) BoolT)], rulesOfProgram = [], assertionsOfProgram = []}
PAtom (AKind Nat (IVar (VString "myNumber")))
PAtom (AKind (KInd (IVarN Business)) (IVar (VString "myBusiness")))
PAtom (AKind (KFun (KInd (IVarN Business)) Boolean) (IVar (VString "is_legal")))
```

**Comment by alfredats** [comment]
If this is acceptable, I'll push it onto main. @mengwong

**Comment by inariksit** [comment]
I've added a pull request for NLG branch with lots of new changes. Which one should we merge first?

**Comment by alfredats** [comment]
Go ahead and merge yours first. It'll give me an excuse to familiarize myself more with the current codebase :)

**Comment by mengwong** [comment]
Sorry, I saw an open pull request for this – I hope merging it didn't cause any trouble.

**Pull request merged**
