### PR TITLE
Add build instructions

### PR DESCRIPTION
**Pull request by kharus**

### CODE REVIEW

**Comment by anka-213** [comment]
The build doesn't actually require a local installation of gf-core, just rgl. But gf-core is a dependency for rgl.

**Comment by inariksit** [comment]
If we want to remove the dependency of RGL, we can commit the PGF in, and just generate the Haskell file `Prop.hs`, because the Haskell is generated only from the abstract syntax, and hence doesn't need the RGL.

**Comment by kharus** [comment]
@inariksit 
Shall we extract it to the beginner friendly issue?

**Comment by kharus** [comment]
@anka-213 I updated documentation to reflect the fact that we depend only on `RGL` but not on `GF`.
I also added [issue](https://github.com/smucclaw/baby-l4/issues/12) to implement @inariksit suggestion.

**Comment by kharus** [comment]
Docs provided during all-hands session

**Pull request closed without merging**
